import { ColumnDefinition } from "../types/tracker";

export interface TrackerTemplate {
  name: string;
  description: string;
  columns: ColumnDefinition[];
  primaryKeyColumn: string;
}

export const defaultTemplates: Record<string, TrackerTemplate> = {
  fashion: {
    name: "Fashion Production Tracker",
    description: "Track SKUs, production status, and delivery dates for fashion items",
    primaryKeyColumn: "sku",
    columns: [
      {
        id: "sku",
        name: "SKU Code",
        key: "sku",
        type: "text",
        required: true,
        order: 0,
        width: 120,
        aiEnabled: true,
        aiAliases: ["sku", "item code", "product code", "style number"],
      },
      {
        id: "product",
        name: "Product Name",
        key: "product",
        type: "text",
        required: true,
        order: 1,
        width: 200,
        aiEnabled: true,
        aiAliases: ["product", "item", "style", "description"],
      },
      {
        id: "season",
        name: "Season",
        key: "season",
        type: "select",
        required: false,
        options: ["SS25", "FW25", "SS26", "FW26"],
        order: 2,
        width: 100,
        aiEnabled: true,
        aiAliases: ["season", "collection"],
      },
      {
        id: "category",
        name: "Category",
        key: "category",
        type: "text",
        required: false,
        order: 3,
        width: 120,
        aiEnabled: true,
        aiAliases: ["category", "type", "product type"],
      },
      {
        id: "color",
        name: "Color",
        key: "color",
        type: "text",
        required: false,
        order: 4,
        width: 100,
      },
      {
        id: "size",
        name: "Size",
        key: "size",
        type: "text",
        required: false,
        order: 5,
        width: 80,
      },
      {
        id: "quantity",
        name: "Quantity",
        key: "quantity",
        type: "number",
        required: false,
        order: 6,
        width: 100,
        aiEnabled: true,
        aiAliases: ["quantity", "qty", "units", "pieces"],
      },
      {
        id: "status",
        name: "Status",
        key: "status",
        type: "select",
        required: false,
        options: ["pending", "in_production", "quality_check", "shipped", "delivered", "delayed"],
        order: 7,
        width: 140,
        aiEnabled: true,
        aiAliases: ["status", "production status", "order status"],
      },
      {
        id: "supplier",
        name: "Supplier",
        key: "supplier",
        type: "text",
        required: false,
        order: 8,
        width: 150,
        aiEnabled: true,
        aiAliases: ["supplier", "vendor", "factory", "manufacturer"],
      },
      {
        id: "tracking",
        name: "Tracking Number",
        key: "tracking",
        type: "text",
        required: false,
        order: 9,
        width: 150,
        aiEnabled: true,
        aiAliases: ["tracking", "tracking number", "tracking #", "shipment number"],
      },
      {
        id: "delivery",
        name: "Delivery Date",
        key: "delivery",
        type: "date",
        required: false,
        order: 10,
        width: 120,
        aiEnabled: true,
        aiAliases: ["delivery date", "arrival date", "eta", "expected delivery"],
      },
      {
        id: "notes",
        name: "Notes",
        key: "notes",
        type: "text",
        required: false,
        order: 11,
        width: 200,
      },
    ],
  },

  logistics: {
    name: "Logistics Tracking",
    description: "Track shipments, carriers, and delivery status",
    primaryKeyColumn: "tracking",
    columns: [
      {
        id: "tracking",
        name: "Tracking Number",
        key: "tracking",
        type: "text",
        required: true,
        order: 0,
        width: 180,
        aiEnabled: true,
        aiAliases: ["tracking", "tracking number", "tracking #", "waybill"],
      },
      {
        id: "carrier",
        name: "Carrier",
        key: "carrier",
        type: "select",
        required: true,
        options: ["UPS", "FedEx", "DHL", "USPS", "TNT", "Other"],
        order: 1,
        width: 120,
        aiEnabled: true,
        aiAliases: ["carrier", "shipping company", "courier"],
      },
      {
        id: "origin",
        name: "Origin",
        key: "origin",
        type: "text",
        required: false,
        order: 2,
        width: 150,
        aiEnabled: true,
        aiAliases: ["origin", "from", "shipped from", "departure"],
      },
      {
        id: "destination",
        name: "Destination",
        key: "destination",
        type: "text",
        required: false,
        order: 3,
        width: 150,
        aiEnabled: true,
        aiAliases: ["destination", "to", "delivery address", "arrival"],
      },
      {
        id: "status",
        name: "Status",
        key: "status",
        type: "select",
        required: false,
        options: ["pending", "picked_up", "in_transit", "out_for_delivery", "delivered", "exception"],
        order: 4,
        width: 140,
        aiEnabled: true,
        aiAliases: ["status", "delivery status", "shipment status"],
      },
      {
        id: "ship_date",
        name: "Ship Date",
        key: "ship_date",
        type: "date",
        required: false,
        order: 5,
        width: 120,
        aiEnabled: true,
        aiAliases: ["ship date", "pickup date", "sent date"],
      },
      {
        id: "eta",
        name: "ETA",
        key: "eta",
        type: "date",
        required: false,
        order: 6,
        width: 120,
        aiEnabled: true,
        aiAliases: ["eta", "expected delivery", "arrival date"],
      },
      {
        id: "delivered",
        name: "Delivered Date",
        key: "delivered",
        type: "date",
        required: false,
        order: 7,
        width: 120,
        aiEnabled: true,
        aiAliases: ["delivered", "delivery date", "received date"],
      },
      {
        id: "recipient",
        name: "Recipient",
        key: "recipient",
        type: "text",
        required: false,
        order: 8,
        width: 150,
      },
      {
        id: "reference",
        name: "Reference",
        key: "reference",
        type: "text",
        required: false,
        order: 9,
        width: 150,
        aiEnabled: true,
        aiAliases: ["reference", "po number", "order number"],
      },
    ],
  },

  simple: {
    name: "Simple Tracker",
    description: "A basic tracker with customizable fields",
    primaryKeyColumn: "id",
    columns: [
      {
        id: "id",
        name: "ID",
        key: "id",
        type: "text",
        required: true,
        order: 0,
        width: 100,
      },
      {
        id: "name",
        name: "Name",
        key: "name",
        type: "text",
        required: true,
        order: 1,
        width: 200,
      },
      {
        id: "status",
        name: "Status",
        key: "status",
        type: "select",
        required: false,
        options: ["active", "pending", "completed", "cancelled"],
        order: 2,
        width: 120,
      },
      {
        id: "date",
        name: "Date",
        key: "date",
        type: "date",
        required: false,
        order: 3,
        width: 120,
      },
      {
        id: "notes",
        name: "Notes",
        key: "notes",
        type: "text",
        required: false,
        order: 4,
        width: 300,
      },
    ],
  },
};