name: CI

on:
  push:
    branches: [ main, master, develop, alex/** ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run CI Checks
        run: |
          chmod +x .github/scripts/ci-runner.sh
          chmod +x .github/checks/*.sh
          .github/scripts/ci-runner.sh
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
        
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - name: Cache Turbo
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
            
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run Type Check
        run: yarn typecheck
        continue-on-error: true  # Don't fail the build on type errors for now
        
      - name: Run Linting
        run: yarn lint
        continue-on-error: true  # Don't fail the build on lint errors for now
        
      - name: Report Status
        if: always()
        run: |
          echo "✅ CI checks completed"
          echo "Note: Type and lint errors are currently non-blocking"
          echo "Consider removing 'continue-on-error' once all issues are fixed"